/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tomgregory;

public class App {
    public String getGreeting() {
        return "Gradle incremental build 4tw!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
